### ISSUE TITLE
mantra create should download Meteor if not found

### ISSUE THREAD

**Issue by merlinstardust** [mantrajs/mantra-cli#34]
I just installed mantra-cli and tried to create a project. The directory was created but nothing else happened. I realized it was because I didn't have Meteor installed. It'd be great if Mantra either downloaded Meteor for you, or if it notified you that Meteor was not installed.

**Comment by sungwoncho** [comment]
Thanks for the suggestion. I think downloading Meteor is the out of the scope of Mantra CLI. Also, it will be tricky to support Windows.

It'd be good if we can output errors back to the user instead of halting silently. I can't think of a good way to do this. But now we have a verbose mode ([doc](https://github.com/mantrajs/mantra-cli#mantra-create-path)), so that people can debug what is going on.
